version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y verilator
      - run: sbt test

#general:
#  branches:
#    only:
#     - master
